spring.application.name=BankManagementSystem
spring.datasource.url=jdbc:postgresql://localhost:5432/bank_system
spring.datasource.username=postgres
spring.datasource.password=project

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true